### PR TITLE
syntax updates for julia v1

### PR DESCRIPTION
**Pull request by maximerischard**

### CODE REVIEW

**Comment by currymj** [comment]
Thanks for doing this! I had forgotten I made this repository. You should make a commit that changes the CI settings in the `.travis.yml` file to a newer version of that (maybe copy from another project) so that it will run tests on 1.0. (Don't worry about 0.7 at this point probably.)

Probably just delete `appveyor.yml`, and the corresponding badge in `README.md` for now.

I will do this eventually if you don't but won't be able to dig into it for a little while. Please put yourself in the "acknowledgements" section too if you want.

**Comment by currymj** [comment]
Actually just sent you an invite for push access, so you can just do things directly instead of waiting for me to merge PRs, if you have any improvements or changes you'd like to make. It is likely you know way more about sampling Pólya-Gamma than I do anyway.

**Comment by currymj** [comment]
@maximerischard still feel like doing this? and did you get the invitation? if you accept it you should be able to merge this yourself if you want.

**Comment by maximerischard** [comment]
Thanks for the invite, and sorry I got busy with some other things this week-end. I've just merged all my commits, including adding pdf and logpdf functions.

**Pull request merged**
